window.ABE_PROJECTS = [
  {
    slug: 'prayer-city',
    title: 'Houston World Cup Prayer City',
    subtitle: 'Volunteer platform · Firebase · Gmail automation',
    category: 'Nonprofit',
    filterTags: ['web-apps', 'automation'],
    shippedLabel: 'Shipped Q1 2025',
    shippedISO: '2025-02-15',
    duration: '6 weeks',
    featured: true,
    sortOrder: 1,
    url: 'https://prayercityhtx.com',
    image: 'images/screenshots/prayer-city/hero.png',
    imageAlt: 'Prayer City volunteer platform homepage',
    socialProof: 'Coordinated 400+ volunteers across World Cup serve days without spreadsheet chaos.',
    problem: 'Hundreds of volunteers across multiple serve days — spreadsheets and manual email lists couldn\'t scale.',
    solution: 'Firebase volunteer hub, shift signup, daily digests, and Gmail/Sheets automation pipelines.',
    metrics: [
      { value: '500+', label: 'Signups in first month' },
      { value: '70%', label: 'Less manual coordination' },
      { value: '12', label: 'Serve days coordinated' },
      { value: '90', label: 'Lighthouse score' },
    ],
    stack: ['Firebase Auth', 'Firestore', 'Cloud Functions', 'Firebase Storage', 'Google Apps Script', 'Gmail API', 'Vercel'],
  },
  {
    slug: 'volunteer-matching-agent',
    title: 'Volunteer Matching Agent',
    subtitle: 'Nonprofit AI · shift matching · human approval',
    category: 'Agentic AI',
    filterTags: ['agentic-ai', 'web-apps'],
    shippedLabel: 'Shipped Q2 2025',
    shippedISO: '2025-05-01',
    duration: '4 weeks',
    featured: true,
    sortOrder: 2,
    url: 'https://prayercityhtx.com',
    image: 'images/screenshots/prayer-city/signup.png',
    imageAlt: 'AI volunteer matching agent interface',
    socialProof: 'Leadership stopped hand-matching volunteers to shifts — the agent drafts matches, humans approve in one click.',
    problem: 'Volunteer coordinators spent hours each week matching skills and availability to open shifts manually.',
    solution: 'Genkit-style agent reads Firestore roster data, proposes shift matches, and queues digest emails after human approval.',
    metrics: [
      { value: '70%', label: 'Reduction in manual matching' },
      { value: '500+', label: 'Signups processed' },
      { value: 'Daily', label: 'Agent-assisted digests' },
      { value: '100%', label: 'Human approval before send' },
    ],
    stack: ['Firebase', 'Cloud Functions', 'Genkit', 'Groq', 'Firestore', 'Gmail API'],
  },
  {
    slug: 'prayer-city-automation',
    title: 'Prayer City Outreach Automation',
    subtitle: 'Gmail · Sheets · scheduled digests',
    category: 'Automation',
    filterTags: ['automation'],
    shippedLabel: 'Shipped Q1 2025',
    shippedISO: '2025-03-01',
    duration: '3 weeks',
    featured: true,
    sortOrder: 3,
    url: 'https://prayercityhtx.com',
    image: 'images/screenshots/prayer-city/signup.png',
    imageAlt: 'Prayer City volunteer signup automation flow',
    socialProof: 'Zero manual digest sends through peak signup season — automation handled 500+ emails per month.',
    problem: 'Daily role content required manual sends every morning; volunteer lists lived in scattered inboxes.',
    solution: 'Apps Script + Cloud Functions pipeline: forms → Sheets → scheduled Gmail digests with bounce handling.',
    metrics: [
      { value: '500+', label: 'Emails processed / mo' },
      { value: '100%', label: 'Digest sends automated' },
      { value: '0', label: 'Manual roster exports' },
      { value: 'Auto', label: 'Bounce handling' },
    ],
    stack: ['Google Apps Script', 'Gmail API', 'Google Sheets', 'Cloud Functions', 'Scheduled triggers'],
  },
  {
    slug: 'royal-wealth-heritage',
    title: 'Royal Wealth Heritage LLC',
    subtitle: 'Next.js site · Academy enrollment · Zoho email',
    category: 'Business',
    filterTags: ['web-apps'],
    shippedLabel: 'Shipped Q4 2025',
    shippedISO: '2025-10-20',
    duration: '7 weeks',
    featured: true,
    sortOrder: 4,
    url: 'https://royalwealthheritage.com',
    image: 'images/screenshots/royal-wealth-heritage/hero.png',
    imageAlt: 'Royal Wealth Heritage LLC homepage',
    socialProof: '"All live in under two months" — polished site, seven-step wizard, and domain email on day one.',
    problem: 'Two business divisions needed credibility online plus enrollment without PDF attachments and email-thread chaos.',
    solution: '11-page Next.js site, 7-step academy wizard, Web3Forms delivery, Zoho Mail on Vercel DNS.',
    metrics: [
      { value: '11', label: 'Custom pages live' },
      { value: '7-step', label: 'Enrollment wizard' },
      { value: '100%', label: 'Forms to inbox' },
      { value: '<8 wks', label: 'Discovery to launch' },
    ],
    stack: ['Next.js', 'React', 'Tailwind CSS', 'Web3Forms', 'Zoho Mail', 'Vercel DNS', 'Open Graph SEO'],
  },
  {
    slug: 'academy-enrollment-agent',
    title: 'Academy Enrollment Intelligence',
    subtitle: 'Small business AI · form triage · follow-up automation',
    category: 'Agentic AI',
    filterTags: ['agentic-ai', 'automation'],
    shippedLabel: 'Shipped Q4 2025',
    shippedISO: '2025-11-01',
    duration: '3 weeks (add-on)',
    featured: true,
    sortOrder: 5,
    url: 'https://royalwealthheritage.com',
    image: 'images/screenshots/royal-wealth-heritage/enrollment.png',
    imageAlt: 'Intelligent enrollment automation dashboard',
    socialProof: 'Enrollment moved from PDF email threads to guided wizard + intelligent follow-up — Helena\'s team replies faster with full context.',
    problem: 'Academy inquiries arrived as unstructured form data; staff manually triaged, chased missing fields, and sent follow-ups by hand.',
    solution: 'Tool-calling agent classifies submissions, flags incomplete enrollments, drafts personalized follow-ups for human review, then sends via Gmail.',
    metrics: [
      { value: '85%', label: 'Faster enrollment triage' },
      { value: '100%', label: 'Inquiries logged & routed' },
      { value: '0', label: 'Lost PDF attachments' },
      { value: 'Human', label: 'Review before every send' },
    ],
    stack: ['Next.js', 'Node.js workers', 'OpenAI', 'Gmail API', 'Web3Forms', 'Google Sheets'],
  },
  {
    slug: 'prayer-city-social',
    title: 'Prayer City Social',
    subtitle: '10 platforms · AI variants · owned stack',
    category: 'Agentic AI',
    filterTags: ['agentic-ai', 'web-apps'],
    shippedLabel: 'Shipped Q4 2025',
    shippedISO: '2025-11-10',
    duration: '10 weeks',
    featured: true,
    sortOrder: 6,
    url: 'https://social.prayercityhtx.com',
    image: 'images/screenshots/prayer-city-social/hero.png',
    imageAlt: 'Prayer City Social publishing dashboard',
    socialProof: '"One compose box, full control, and we own the entire stack" — ten platforms, no per-seat SaaS fees.',
    problem: 'Posting to ten platforms by hand was slow; subscription schedulers were expensive and capped integrations.',
    solution: 'Next.js dashboard with AI variants per network, OAuth to 10 channels, queue workers for publish and retry.',
    metrics: [
      { value: '10', label: 'Social platforms' },
      { value: '$1.2K+', label: 'Annual SaaS avoided' },
      { value: '3', label: 'LLM providers w/ failover' },
      { value: '1', label: 'Compose → publish flow' },
    ],
    stack: ['Next.js', 'PocketBase', 'Queue workers', 'Groq', 'OpenAI', 'OAuth 2.0', 'Cloudflare Tunnel'],
  },
  {
    slug: 'agentic-publishing',
    title: 'Agentic Publishing Layer',
    subtitle: 'Multi-LLM agents · queue workers · human review',
    category: 'Agentic AI',
    filterTags: ['agentic-ai'],
    shippedLabel: 'Shipped Q4 2025',
    shippedISO: '2025-11-15',
    duration: '4 weeks (add-on)',
    featured: true,
    sortOrder: 7,
    url: 'https://social.prayercityhtx.com',
    image: 'images/screenshots/prayer-city-social/dashboard.png',
    imageAlt: 'Agentic publishing command center',
    socialProof: 'One compose action produces ten network-ready variants in seconds — provider outages no longer block publishing.',
    problem: 'Each social network needs different tone, length, and format — single-provider AI APIs fail without fallbacks.',
    solution: 'Agent orchestration with platform prompt templates, multi-LLM failover, queue workers, and human review gates.',
    metrics: [
      { value: '10', label: 'Variants per compose' },
      { value: '3', label: 'LLM providers' },
      { value: '70%', label: 'Less manual rewriting' },
      { value: 'Owned', label: 'Full stack control' },
    ],
    stack: ['Agent orchestration', 'Groq', 'DeepSeek', 'OpenAI', 'Node.js workers', 'PocketBase', 'Prompt pipelines'],
  },
  {
    slug: 'firebase-form-starter',
    title: 'Firebase Form Starter Kit',
    subtitle: 'Open-source pattern · spam protection · inbox delivery',
    category: 'Open source',
    filterTags: ['web-apps'],
    shippedLabel: 'Shipped Q2 2025',
    shippedISO: '2025-06-01',
    duration: 'Reference kit',
    featured: false,
    sortOrder: 8,
    url: 'https://github.com/Dabe90',
    image: 'images/screenshots/royal-wealth-heritage/enrollment.png',
    imageAlt: 'Form enrollment pattern from starter kit',
    socialProof: 'Reusable pattern shipped on multiple client projects — prospects inspect the code before hiring.',
    problem: 'Static sites need reliable form delivery without standing up a backend or paying form SaaS on every project.',
    solution: 'HTML templates with honeypot spam protection, Web3Forms/FormSubmit integration, optional Firebase path.',
    metrics: [
      { value: 'Honeypot', label: 'Spam protection' },
      { value: 'Inbox', label: 'Direct delivery' },
      { value: 'Static', label: 'No server required' },
      { value: 'OSS', label: 'Free to fork' },
    ],
    stack: ['HTML', 'Web3Forms', 'Firebase', 'FormSubmit', 'Tailwind CSS'],
  },
  {
    slug: 'abe-stack-site',
    title: 'Abe Stack Marketing Site',
    subtitle: 'SEO · Lighthouse 90+ · lead gen funnel',
    category: 'Studio',
    filterTags: ['web-apps'],
    shippedLabel: 'Shipped Q1 2026',
    shippedISO: '2026-01-15',
    duration: 'Ongoing',
    featured: false,
    sortOrder: 9,
    url: 'https://abestack.com',
    image: 'images/og-image.png',
    imageAlt: 'Abe Stack marketing site',
    socialProof: 'Prospects see real work, transparent pricing, and production Lighthouse scores before the first call.',
    problem: 'A technology studio needs a site that proves craft — not a template that looks like every other agency.',
    solution: 'Premium static site with case studies, JSON-LD SEO, FormSubmit + Calendly lead capture, and Zoho Mail.',
    metrics: [
      { value: '90+', label: 'Lighthouse performance' },
      { value: '100', label: 'SEO score' },
      { value: '10', label: 'Case studies live' },
      { value: '48hr', label: 'Quote response SLA' },
    ],
    stack: ['Static HTML', 'Tailwind CSS', 'FormSubmit', 'Calendly', 'Zoho Mail', 'Vercel', 'JSON-LD SEO'],
  },
  {
    slug: 'launch-checklist',
    title: 'Production Launch Checklist',
    subtitle: 'Lead magnet · FormSubmit · resource funnel',
    category: 'Lead gen',
    filterTags: ['web-apps', 'automation'],
    shippedLabel: 'Shipped Q1 2026',
    shippedISO: '2026-01-10',
    duration: '1 week',
    featured: false,
    sortOrder: 10,
    url: 'https://abestack.com/resources/',
    image: 'images/og-image.png',
    imageAlt: 'Production launch checklist resource',
    socialProof: 'Prospects who download the checklist arrive informed — shorter discovery, faster scoping.',
    problem: 'Teams don\'t know what a production launch includes until go-live week panic sets in.',
    solution: 'Gated checklist covering DNS, SSL, email, forms, SEO, and handoff — with FormSubmit capture funnel.',
    metrics: [
      { value: '25+', label: 'Launch checkpoints' },
      { value: 'Free', label: 'Gated download' },
      { value: 'SEO', label: 'Indexed resource pages' },
      { value: 'Form', label: 'Lead capture live' },
    ],
    stack: ['FormSubmit', 'Static HTML', 'Google Search Console', 'Structured metadata'],
  },
];

window.ABE_PROJECT_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'web-apps', label: 'Web Apps' },
  { id: 'automation', label: 'Automation' },
  { id: 'agentic-ai', label: 'Agentic AI' },
];
