window.ABE_PROJECTS = [
  {
    slug: 'prayer-city',
    title: 'Houston World Cup Prayer City',
    subtitle: 'Volunteer ops · Firebase · Gmail automation',
    category: 'Nonprofit',
    shippedLabel: 'Shipped Feb 2025',
    shippedISO: '2025-02-15',
    duration: '6 weeks',
    featured: true,
    sortOrder: 1,
    url: 'https://prayercityhtx.com',
    image: 'images/screenshots/prayer-city/hero.png',
    imageAlt: 'Prayer City volunteer platform homepage',
    metrics: [
      { value: '400+', label: 'Volunteer signups' },
      { value: '12', label: 'Serve days coordinated' },
      { value: 'Daily', label: 'Role digests automated' },
      { value: '90', label: 'Lighthouse performance' },
    ],
    stack: ['Firebase Auth', 'Firestore', 'Cloud Functions', 'Firebase Storage', 'Google Apps Script', 'Gmail API', 'Vercel'],
  },
  {
    slug: 'royal-wealth-heritage',
    title: 'Royal Wealth Heritage LLC',
    subtitle: 'Next.js site · Academy enrollment · Zoho email',
    category: 'Business',
    shippedLabel: 'Shipped Oct 2025',
    shippedISO: '2025-10-20',
    duration: '7 weeks',
    featured: true,
    sortOrder: 2,
    url: 'https://royalwealthheritage.com',
    image: 'images/screenshots/royal-wealth-heritage/hero.png',
    imageAlt: 'Royal Wealth Heritage LLC homepage',
    metrics: [
      { value: '11', label: 'Custom pages live' },
      { value: '7-step', label: 'Enrollment wizard' },
      { value: '100%', label: 'Forms to inbox' },
      { value: '<8 wks', label: 'Discovery to launch' },
    ],
    stack: ['Next.js', 'React', 'Tailwind CSS', 'Web3Forms', 'Zoho Mail', 'Vercel DNS', 'Open Graph SEO'],
  },
  {
    slug: 'prayer-city-social',
    title: 'Prayer City Social',
    subtitle: '10 platforms · AI variants · owned stack',
    category: 'AI & SaaS',
    shippedLabel: 'Shipped Nov 2025',
    shippedISO: '2025-11-10',
    duration: '10 weeks',
    featured: true,
    sortOrder: 3,
    url: 'https://social.prayercityhtx.com',
    image: 'images/screenshots/prayer-city-social/hero.png',
    imageAlt: 'Prayer City Social publishing dashboard',
    metrics: [
      { value: '10', label: 'Social platforms' },
      { value: '3', label: 'LLM providers w/ failover' },
      { value: '1', label: 'Compose → publish flow' },
      { value: '$1.2K+', label: 'Annual SaaS avoided' },
    ],
    stack: ['Next.js', 'PocketBase', 'Queue workers', 'Groq', 'OpenAI', 'OAuth 2.0', 'Cloudflare Tunnel'],
  },
  {
    slug: 'prayer-city-automation',
    title: 'Prayer City Outreach Automation',
    subtitle: 'Gmail · Sheets · scheduled digests',
    category: 'Automation',
    shippedLabel: 'Shipped Mar 2025',
    shippedISO: '2025-03-01',
    duration: '3 weeks',
    featured: true,
    sortOrder: 4,
    url: 'https://prayercityhtx.com',
    image: 'images/screenshots/prayer-city/signup.png',
    imageAlt: 'Prayer City volunteer signup automation flow',
    metrics: [
      { value: '500+', label: 'Emails processed / mo' },
      { value: '0', label: 'Manual digest sends' },
      { value: 'Auto', label: 'Bounce handling' },
      { value: 'Sheets', label: 'Live volunteer roster' },
    ],
    stack: ['Google Apps Script', 'Gmail API', 'Google Sheets', 'Cloud Functions', 'Scheduled triggers'],
  },
  {
    slug: 'agentic-publishing',
    title: 'Agentic Publishing Layer',
    subtitle: 'Multi-LLM agents · queue workers · human review',
    category: 'Agentic AI',
    shippedLabel: 'Shipped Nov 2025',
    shippedISO: '2025-11-15',
    duration: '4 weeks (add-on)',
    featured: true,
    sortOrder: 5,
    url: 'https://social.prayercityhtx.com',
    image: 'images/screenshots/prayer-city-social/dashboard.png',
    imageAlt: 'Agentic publishing command center',
    metrics: [
      { value: '10', label: 'Platform-specific variants' },
      { value: '3', label: 'LLM providers' },
      { value: 'Queue', label: 'Retry + scheduling' },
      { value: 'Owned', label: 'Full stack control' },
    ],
    stack: ['Agent orchestration', 'Groq', 'DeepSeek', 'OpenAI', 'Node.js workers', 'PocketBase', 'Prompt pipelines'],
  },
  {
    slug: 'abe-stack-site',
    title: 'Abe Stack Marketing Site',
    subtitle: 'SEO · Lighthouse 90+ · lead gen funnel',
    category: 'Studio',
    shippedLabel: 'Shipped Jan 2026',
    shippedISO: '2026-01-15',
    duration: 'Ongoing',
    featured: true,
    sortOrder: 6,
    url: 'https://abestack.com',
    image: 'images/og-image.png',
    imageAlt: 'Abe Stack marketing site',
    metrics: [
      { value: '90+', label: 'Lighthouse performance' },
      { value: '100', label: 'SEO score' },
      { value: '8', label: 'Case studies published' },
      { value: '48hr', label: 'Quote response SLA' },
    ],
    stack: ['Static HTML', 'Tailwind CSS', 'FormSubmit', 'Calendly', 'Zoho Mail', 'Vercel', 'JSON-LD SEO'],
  },
  {
    slug: 'launch-checklist',
    title: 'Production Launch Checklist',
    subtitle: 'Lead magnet · FormSubmit · resource funnel',
    category: 'Lead gen',
    shippedLabel: 'Shipped Jan 2026',
    shippedISO: '2026-01-10',
    duration: '1 week',
    featured: false,
    sortOrder: 7,
    url: 'https://abestack.com/resources/',
    image: 'images/og-image.png',
    imageAlt: 'Production launch checklist resource',
    metrics: [
      { value: '25+', label: 'Launch checkpoints' },
      { value: 'DNS', label: 'Email · SSL · forms' },
      { value: 'Free', label: 'Gated download' },
      { value: 'SEO', label: 'Indexed resource pages' },
    ],
    stack: ['FormSubmit', 'Static HTML', 'Google Search Console', 'Structured metadata'],
  },
  {
    slug: 'firebase-form-starter',
    title: 'Firebase Form Starter Kit',
    subtitle: 'Open-source pattern · spam protection · inbox delivery',
    category: 'Open source',
    shippedLabel: 'Shipped Jun 2025',
    shippedISO: '2025-06-01',
    duration: 'Reference kit',
    featured: false,
    sortOrder: 8,
    url: 'https://github.com/Dabe90',
    image: 'images/screenshots/royal-wealth-heritage/enrollment.png',
    imageAlt: 'Form enrollment pattern from starter kit',
    metrics: [
      { value: 'Honeypot', label: 'Spam protection' },
      { value: 'Inbox', label: 'Direct form delivery' },
      { value: 'Static', label: 'No backend required' },
      { value: 'OSS', label: 'Free to fork' },
    ],
    stack: ['HTML', 'Web3Forms', 'Firebase', 'FormSubmit', 'Tailwind CSS'],
  },
];
